version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: linguacards-postgres
    environment:
      POSTGRES_DB: linguacards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - linguacards-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linguacards-app
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - linguacards-network
#    volumes:
#      - ./certs:/app/certs

volumes:
  postgres_data:

networks:
  linguacards-network:
    driver: bridge